# Generated by Django 5.1.4 on 2024-12-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reports',
            new_name='Report',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='mag',
            new_name='lng',
        ),
    ]
